-- Run once as a DBA inside the pluggable database. In Oracle a "schema" is a user.
-- NOT YET VERIFIED against a live Oracle instance (first CI run will exercise it).
CREATE USER stg IDENTIFIED BY "ChangeMe_stg1" QUOTA UNLIMITED ON USERS;
CREATE USER mst IDENTIFIED BY "ChangeMe_mst1" QUOTA UNLIMITED ON USERS;
CREATE USER aml IDENTIFIED BY "ChangeMe_aml1" QUOTA UNLIMITED ON USERS;
CREATE USER fisre IDENTIFIED BY "fisre" QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE ANY TABLE, CREATE ANY INDEX,
      SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO fisre;
