-- STG: landing area loaded by the bank's ETL. Typed but unconstrained; the engine validates and promotes.
-- rec_status: NEW -> PROCESSED | REJECTED
CREATE TABLE ${stg}.customer (
    stg_id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id               VARCHAR2(40),
    rec_status            VARCHAR2(10) DEFAULT 'NEW' NOT NULL,
    reject_reason         VARCHAR2(400),
    customer_id           VARCHAR2(40),
    customer_type         VARCHAR2(20),
    full_name             VARCHAR2(200),
    birth_or_formation_dt DATE,
    country_code          VARCHAR2(3),
    state_code            VARCHAR2(3),
    customer_since        DATE,
    status                VARCHAR2(20)
);
CREATE INDEX ${stg}.ix_stg_customer_status ON ${stg}.customer (rec_status);
CREATE INDEX ${stg}.ix_stg_customer_key ON ${stg}.customer (customer_id);

CREATE TABLE ${stg}.account (
    stg_id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id             VARCHAR2(40),
    rec_status          VARCHAR2(10) DEFAULT 'NEW' NOT NULL,
    reject_reason       VARCHAR2(400),
    account_id          VARCHAR2(40),
    primary_customer_id VARCHAR2(40),
    product_type        VARCHAR2(20),
    product_subtype     VARCHAR2(40),
    status              VARCHAR2(20),
    open_date           DATE,
    close_date          DATE,
    currency            VARCHAR2(3),
    branch_code         VARCHAR2(20),
    credit_limit        NUMBER(19,4)
);
CREATE INDEX ${stg}.ix_stg_account_status ON ${stg}.account (rec_status);
CREATE INDEX ${stg}.ix_stg_account_key ON ${stg}.account (account_id);

CREATE TABLE ${stg}.txn (
    stg_id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id               VARCHAR2(40),
    rec_status            VARCHAR2(10) DEFAULT 'NEW' NOT NULL,
    reject_reason         VARCHAR2(400),
    transaction_id        VARCHAR2(60),
    account_id            VARCHAR2(40),
    txn_ts                TIMESTAMP(6),
    posting_date          DATE,
    txn_type              VARCHAR2(30),
    direction             VARCHAR2(6),
    amount                NUMBER(19,4),
    currency              VARCHAR2(3),
    channel               VARCHAR2(20),
    counterparty_name     VARCHAR2(200),
    counterparty_account  VARCHAR2(60),
    counterparty_country  VARCHAR2(3),
    merchant_category_code VARCHAR2(4),
    description           VARCHAR2(400)
);
CREATE INDEX ${stg}.ix_stg_txn_status ON ${stg}.txn (rec_status);
CREATE INDEX ${stg}.ix_stg_txn_key ON ${stg}.txn (transaction_id);
