INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('CASH_DEPOSIT', 'Y', 'Cash deposited to deposit account');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('CASH_WITHDRAWAL', 'Y', 'Cash withdrawn from deposit account');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('CARD_CASH_ADVANCE', 'Y', 'Cash advance on a card account');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('CHECK_DEPOSIT', 'N', 'Check deposit');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('ACH_CREDIT', 'N', 'ACH credit');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('ACH_DEBIT', 'N', 'ACH debit');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('WIRE_IN', 'N', 'Incoming wire');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('WIRE_OUT', 'N', 'Outgoing wire');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('INTERNAL_TRANSFER', 'N', 'Transfer between accounts at the bank');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('POS_PURCHASE', 'N', 'Card purchase, point of sale');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('ECOM_PURCHASE', 'N', 'Card purchase, e-commerce');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('CARD_PAYMENT', 'N', 'Payment toward a card balance');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('LOAN_DISBURSEMENT', 'N', 'Loan funds disbursed');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('LOAN_PAYMENT', 'N', 'Scheduled or extra loan payment');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('LOAN_PAYOFF', 'N', 'Loan paid off in full');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('FEE', 'N', 'Fee');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('INTEREST', 'N', 'Interest posted or charged');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('REFUND', 'N', 'Refund');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('REVERSAL', 'N', 'Reversal of a prior transaction');
INSERT INTO ${mst}.ref_txn_type (txn_type, is_cash, description) VALUES ('OTHER', 'N', 'Other');
